"""
raiku export  — dump installed packages to requirements.raiku
raiku import  — install all packages listed in requirements.raiku

File format (requirements.raiku):

    # comment
    fast-math==1.0.0         # Python  --hash sha256:abc123...
    goqueue==1.0.0            # Go
    blazing-vec==1.0.0        # Rust
"""
from __future__ import annotations

from pathlib import Path

import click
from rich.console import Console

from core.config import RaikuConfig
from installer.cache_store import CacheStore

DEFAULT_FILE = "requirements.raiku"


# ---------------------------------------------------------------------------
# export
# ---------------------------------------------------------------------------

@click.command("export")
@click.option("--output", "-o", default=DEFAULT_FILE,
              help=f"Output file (default: {DEFAULT_FILE}).")
@click.option("--language", "-l", default=None, help="Export only one language.")
@click.pass_context
def export_cmd(ctx: click.Context, output: str, language: str | None) -> None:
    """Export installed packages to a requirements file."""
    cfg: RaikuConfig = ctx.obj["config"]
    console: Console = ctx.obj["console"]

    store = CacheStore(cfg.cache_dir)
    packages = store.list_installed()

    if language:
        packages = [p for p in packages if p.get("language", "").lower() == language.lower()]

    if not packages:
        console.print("[yellow]No packages installed to export.[/yellow]")
        return

    lines = [
        "# Raiku requirements file",
        "# Generated by: raiku export",
        "# Install with: raiku import",
        "",
    ]
    for pkg in sorted(packages, key=lambda p: p.get("name", "")):
        line = f"{pkg['name']}=={pkg['version']}  # {pkg.get('language', '?')}"
        if pkg.get("sha256"):
            line += f"  --hash sha256:{pkg['sha256']}"
        lines.append(line)

    Path(output).write_text("\n".join(lines) + "\n", encoding="utf-8")
    console.print(
        f"[green]✓[/green] Exported {len(packages)} package(s) to [cyan]{output}[/cyan]"
    )


# ---------------------------------------------------------------------------
# import
# ---------------------------------------------------------------------------

@click.command("import")
@click.option("--file", "-f", "req_file", default=DEFAULT_FILE,
              help=f"Requirements file to read (default: {DEFAULT_FILE}).")
@click.option("--trust", is_flag=True, default=False,
              help="Skip build confirmation for all packages.")
@click.option("--no-build", is_flag=True, default=False,
              help="Download only, skip builds.")
@click.pass_context
def import_cmd(ctx: click.Context, req_file: str, trust: bool, no_build: bool) -> None:
    """Install all packages listed in a requirements file."""
    cfg: RaikuConfig = ctx.obj["config"]
    console: Console = ctx.obj["console"]

    path = Path(req_file)
    if not path.exists():
        console.print(f"[red]File '{req_file}' not found.[/red]")
        raise click.exceptions.Exit(1)

    entries: list[dict] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        line = line.split("#")[0].strip()
        parts = line.split()
        if not parts:
            continue
        pkg_spec = parts[0]
        name, _, version = pkg_spec.partition("==")
        entries.append({"name": name.strip(), "version": version.strip() or None})

    if not entries:
        console.print("[yellow]No packages found in file.[/yellow]")
        return

    console.print(
        f"[bold cyan]Installing {len(entries)} package(s) from {req_file}[/bold cyan]\n"
    )

    from cli.commands.install import install_cmd

    success = 0
    for entry in entries:
        label = entry["name"]
        if entry["version"]:
            label += f" v{entry['version']}"
        console.print(f"  → [bold]{label}[/bold]")
        try:
            ctx.invoke(
                install_cmd,
                package=entry["name"],
                trust=trust,
                no_build=no_build,
                force=False,
                no_deps=False,
                use_lock=False,
            )
            success += 1
        except SystemExit as exc:
            if exc.code != 0:
                console.print(f"    [red]Failed (exit {exc.code})[/red]")
        except Exception as exc:
            console.print(f"    [red]Failed: {exc}[/red]")

    console.print(
        f"\n[bold green]✓ Installed {success}/{len(entries)} package(s).[/bold green]"
    )
